#!/bin/bash

start() {
    sphinx-autobuild -a /docs/$PROJECT_NAME/source/ /docs/$PROJECT_NAME/build/html &>/dev/null
}

stop() {
        PID=$(pgrep sphinx-autobuild*) && kill $PID
}

case "$1" in
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    status)
       status sphinx-autobuild
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0
