#!/bin/bash

### BEGIN INIT INFO
# Provides:          autosphinx
# Required-Start:    $all
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Initiates sphinx-autobuild server
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/nginx
NAME=autosphinx
DESC=autosphinx
PROJ=$(ls -d /sphinx/projects/*)
PROJ_NUM=$(ls /sphinx/projects | wc -l)
PROJ_NAME=$(ls /sphinx/projects)
PROJ_DEF=/sphinx/default
SRC=sphinx/projects/$PROJ/source
DST=sphinx/projects/$PROJ/build/html

# Create temporary file PROJ.txt
ls -d /sphinx/projects/* > /sphinx/PROJ.txt

STOP_SCHEDULE="${STOP_SCHEDULE:-QUIT/5/TERM/5/KILL/5}"

# Try to extract nginx pidfile
PID=$(pgrep sphinx-autobuild*)

case "$1" in
    start) sphinx-autobuild -a $SRC $DST &> /dev/null &
    start) if [[ "$PROJ_NUM" -gt "1" ]]
        then 
            sphinx-autobuild --port=0 -a $PROJ_DEF/source $PROJ_N/build/html &> /dev/null &
            while IFS= read -r LINE; do sphinx-autobuild --port=0 -a $LINE/source $LINE/build/html; done < /sphinx/PROJ.txt &> /dev/null &
        else
            sphinx-autobuild -a $SRC $DST &> /dev/null &
        fi
       ;;
    stop)
       kill $PID
       ;;
    restart)
       $0 stop
       $0 start
       ;;
    status)
       status_of_proc -p && exit 0 || exit $?
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac
