name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASS
    - name: docker build version
      run: docker build . -t redteamcafe/sphinx-rtd:1.0.0
    - name: docker build latest
      run: docker build . -t redteamcafe/sphinx-rtd:latest
    - name: docker push version
      run: docker push redteamcafe/sphinx-rtd:1.0.0
    - name: docker push latest
      run: docker push redteamcafe/sphinx-rtd:latest
