name: Docker Image CI

on:
  push:
    branches:
      - 'test'
    paths-ignore:
      - '**/.github'
      - '**/.dockerignore'
      - '**/LICENSE'
      - '**/README.md'
#  pull_request:
#    branches:
#      - 'test'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v3
    - name: Setup QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with: 
        image: tonistiigi/binfmt:latest
        platforms: all
    - name: Setup Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest
    - name: Login to Docker Hub
      env:
        USER: ${{ secrets.DOCKER_USER }}
        PASS: ${{ secrets.DOCKER_PASS }}
      run: docker login -u $USER -p $PASS
      
    - name: Build Images
      run: |
        docker buildx build --push \
          --tag redteamcafe/sphinx-rtd:test \
          --platform linux/amd64,linux/arm/v7,linux/arm64/v8 .
